// @generated Code generated by gen-atomicwrapper.

// Copyright (c) 2020-2026 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package atomic

import (
	"encoding/json"
)

// Uint16 is an atomic type-safe wrapper for uint16 values.
type Uint16 struct {
	_ nocmp // disallow non-atomic comparison

	v Uint32
}

var _zeroUint16 uint16

// NewUint16 creates a new Uint16.
func NewUint16(val uint16) *Uint16 {
	x := &Uint16{}
	if val != _zeroUint16 {
		x.Store(val)
	}
	return x
}

// Load atomically loads the wrapped uint16.
func (x *Uint16) Load() uint16 {
	return unpackUint16(x.v.Load())
}

// Store atomically stores the passed uint16.
func (x *Uint16) Store(val uint16) {
	x.v.Store(packUint16(val))
}

// CAS is an atomic compare-and-swap for uint16 values.
//
// Deprecated: Use CompareAndSwap.
func (x *Uint16) CAS(old, new uint16) (swapped bool) {
	return x.CompareAndSwap(old, new)
}

// CompareAndSwap is an atomic compare-and-swap for uint16 values.
func (x *Uint16) CompareAndSwap(old, new uint16) (swapped bool) {
	return x.v.CompareAndSwap(packUint16(old), packUint16(new))
}

// Swap atomically stores the given uint16 and returns the old
// value.
func (x *Uint16) Swap(val uint16) (old uint16) {
	return unpackUint16(x.v.Swap(packUint16(val)))
}

// MarshalJSON encodes the wrapped uint16 into JSON.
func (x *Uint16) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.Load())
}

// UnmarshalJSON decodes a uint16 from JSON.
func (x *Uint16) UnmarshalJSON(b []byte) error {
	var v uint16
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	x.Store(v)
	return nil
}
