// @generated Code generated by gen-atomicwrapper.

// Copyright (c) 2020-2026 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package atomic

import (
	"encoding/json"
)

// Uint8 is an atomic type-safe wrapper for uint8 values.
type Uint8 struct {
	_ nocmp // disallow non-atomic comparison

	v Uint32
}

var _zeroUint8 uint8

// NewUint8 creates a new Uint8.
func NewUint8(val uint8) *Uint8 {
	x := &Uint8{}
	if val != _zeroUint8 {
		x.Store(val)
	}
	return x
}

// Load atomically loads the wrapped uint8.
func (x *Uint8) Load() uint8 {
	return unpackUint8(x.v.Load())
}

// Store atomically stores the passed uint8.
func (x *Uint8) Store(val uint8) {
	x.v.Store(packUint8(val))
}

// CAS is an atomic compare-and-swap for uint8 values.
//
// Deprecated: Use CompareAndSwap.
func (x *Uint8) CAS(old, new uint8) (swapped bool) {
	return x.CompareAndSwap(old, new)
}

// CompareAndSwap is an atomic compare-and-swap for uint8 values.
func (x *Uint8) CompareAndSwap(old, new uint8) (swapped bool) {
	return x.v.CompareAndSwap(packUint8(old), packUint8(new))
}

// Swap atomically stores the given uint8 and returns the old
// value.
func (x *Uint8) Swap(val uint8) (old uint8) {
	return unpackUint8(x.v.Swap(packUint8(val)))
}

// MarshalJSON encodes the wrapped uint8 into JSON.
func (x *Uint8) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.Load())
}

// UnmarshalJSON decodes a uint8 from JSON.
func (x *Uint8) UnmarshalJSON(b []byte) error {
	var v uint8
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	x.Store(v)
	return nil
}
